#!/system/bin/sh
/system/bin/setprop "net.interfaces.defaultroute" "pppoe"
/system/bin/setprop "net.pppoe.dns1" "$DNS1"
/system/bin/setprop "net.pppoe.dns2" "$DNS2"
/system/bin/setprop "net.dns1" "$DNS1"
/system/bin/setprop "net.dns2" "$DNS2"
/system/bin/setprop "net.ppp9.gw" "$IPLOCAL"
/system/bin/setprop "net.ppp9.dns1" "$DNS1"
/system/bin/setprop "net.ppp9.dns2" "$DNS2"
/system/bin/setprop "net.pppoe.local-ip" "$IPLOCAL"
/system/bin/setprop "net.pppoe.remote-ip" "$IPREMOTE"
exit 0 

